# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
  phpVersion: 7.2

steps:
- bash: |
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- task: MysqlDeploymentOnMachineGroup@1
  displayName: 'Deploy Using : InlineSqlTask'
  inputs:
    TaskNameSelector: InlineSqlTask
    SqlInline: |
     CREATE DATABASE IF NOT EXISTS alm;
     use alm;
    ServerName: localhost
    SqlUsername: root
    SqlPassword: P2ssw0rd

- bash: |
    mysql --version
  displayName: 'MySQL Version'

- bash: |
    cp .env.example .env
  displayName: 'Environment Setup'

- bash: |
    composer global require hirak/prestissimo
    composer install --no-interaction --prefer-dist --no-suggest
    composer --version
  displayName: 'Installing Package Dependencies'

- bash: |
    php artisan key:generate
  displayName: 'Running Laravel Artisan'

- bash: |
    phpunit
  displayName: 'Running Unit Tests'
