# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
  phpVersion: 7.2

steps:
- bash: |
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- bash: |
    sudo apt-get install -y mysql-server
    sudo mysql -uroot -proot -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    sudo mysql -u root -e 'create database urlhub_test;'
  displayName: 'Installing System Dependencies'

- bash: |
    mysql --version
  displayName: 'MySQL Version'

- bash: |
    cp .env.example .env
  displayName: 'Environment Setup'

- bash: |
    composer global require hirak/prestissimo
    composer install --no-interaction --prefer-dist --no-suggest
    composer --version
  displayName: 'Installing Package Dependencies'

- bash: |
    php artisan key:generate
  displayName: 'Running Laravel Artisan'

- bash: |
    phpunit
  displayName: 'Running Unit Tests'
